<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Datasets\Create\" />
    <None Remove="Dataset\" />
    <None Remove="Results\" />
    <None Remove="Common\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Dataset\Create\" />
    <Folder Include="Results\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
  </ItemGroup>
</Project>
